MiTestAspIdentity.Web/Controllers/CuentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MiTestAspIdentity.SQL.Model;
using MiTestAspIdentity.Web.Model;
using SignInResult = Microsoft.AspNetCore.Identity.SignInResult;

namespace MiTestAspIdentity.Web.Controllers
{
    public class CuentaController:Controller
    {
        private readonly UserManager<Usuario> _userManager;
        private readonly SignInManager<Usuario> _signInManager;

        public CuentaController(UserManager<Usuario> userManager,
            SignInManager<Usuario> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Ingresar(LoginDto loginDto)
        {
            SignInResult resultLogin =
                await _signInManager.PasswordSignInAsync(loginDto.Usuario, loginDto.Password, true, false);

            if (resultLogin.Succeeded)
            {
                return RedirectToAction("Privado", "Home");
            }
            else
            {
                TempData["error"] = "login invalido";

                return RedirectToAction("Login");
            }
        }

        [HttpGet]
        public IActionResult CrearUsuario()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GuardarUsuario(GuardarUsuarioDto guardarUsuario)
        {
            Usuario usuario = new Usuario()
            {
                Nombre = guardarUsuario.Nombre,
                Apellido = guardarUsuario.Apellido,
                Email = guardarUsuario.Email,
                UserName = guardarUsuario.UserName,
                Id = guardarUsuario.UserName
            };


            await _userManager.CreateAsync(usuario, guardarUsuario.Password);

            List<Claim> claims = new List<Claim>();
            claims.Add(new Claim(ClaimTypes.Role,"rol1"));
            claims.Add(new Claim(ClaimTypes.Surname,usuario.Apellido));
            claims.Add(new Claim(ClaimTypes.GivenName,usuario.Nombre));
            claims.Add(new Claim(ClaimTypes.Email,usuario.Email));
            claims.Add(new Claim("cuenta","fd54f5d"));
            await _userManager.AddClaimsAsync(usuario, claims);

            return RedirectToAction("Login");

        }


    }
}

MiTestAspIdentity.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MiTestAspIdentity.Web.Controllers
{
    public class HomeController: Controller
    {
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            await Task.Delay(1);

            return View();
        }

        [Authorize]
        public IActionResult Privado()
        {
            return View();
        }
    }
}

MiTestAspIdentity.Web/Views/Cuenta/CrearUsuario.cshtml
@model MiTestAspIdentity.Web.Model.GuardarUsuarioDto
@{
    ViewData["Title"] = "CrearUsuario";
}

<h1>Crear Usuario</h1>

<form asp-controller="Cuenta" asp-action="GuardarUsuario">
    <label asp-for="Nombre">Nombre: </label>
    <input type="text" asp-for="Nombre"/>
    <br/>
    <label asp-for="Apellido">Apellido: </label>
    <input asp-for="Apellido"/>
    <br />
    <label asp-for="Email">Correo: </label>
    <input type="email" asp-for="Email"/>
    <br />
    <label asp-for="UserName">Nombre usuario: </label>
    <input asp-for="UserName"/>
    <br/>
    <label asp-for="Password">Password: </label>
    <input asp-for="Password" type="password"/>
    <br/>
    <button type="submit">Enviar</button>
</form>

MiTestAspIdentity.Web/Views/Cuenta/Login.cshtml
@model MiTestAspIdentity.Web.Model.LoginDto
@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>

<form asp-controller="Cuenta" asp-action="Ingresar">
    <label asp-for="Usuario">Usuario: </label>
    <input asp-for="Usuario"/>
    <br/>
    <label>Password: </label>
    <input type="password" asp-for="Password"/>
    <br/>
    <button type="submit">Ingresar</button>
</form>

MiTestAspIdentity.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>Este es el home index</p>

MiTestAspIdentity.Web/Views/Home/Privado.cshtml
@using System.Security.Claims

@{
    ViewData["Title"] = "Privado";
}

<h1>Privado</h1>


<h2>Si estas leyendo esto, es porque te pudiste loguear. Acá tus datos: </h2>
<ul>
    <li>Nombre: @User.Claims.First(x => x.Type == ClaimTypes.GivenName).Value</li>
    <li>Apellido: @User.Claims.First(x => x.Type == ClaimTypes.Surname).Value</li>
    <li>Correo: @User.Claims.First(x => x.Type == ClaimTypes.Email).Value</li>
    <li>Cuenta: @User.Claims.First(x => x.Type == "cuenta").Value</li>
</ul>

MiTestAspIdentity.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>

<div>
    <a asp-action="Login" asp-controller="Cuenta">Ingresar</a>
</div>
<div>
    <a asp-action="CrearUsuario" asp-controller="Cuenta">Registrar usuario</a>
</div>

<div>
    @RenderBody()
</div>
</body>
</html>